---
- name: install cups
  apt:
    name: cups
    state: latest

- name: enable cups interface from the outside by deploying default config
  copy:
    src: cupsd.conf
    dest: /etc/cups/cupsd.conf

- name: restart cups
  service:
    name: cups
    state: restarted

